const express = require("express");
const signupRoute = require("./routeList/signup");
const signinRoute = require("./routeList/signin");
const createNewProject = require("./routeList/createNewProject");
const authenticateToken = require("./middleware/authenticateToken");
const retrieveProject = require("./routeList/retrieveProject");
const editDetail = require("./routeList/editProjectDetail");
const deleteProject = require("./routeList/deleteProject");
const uploadVideo = require("./routeList/uploadVideo");
const videoDisplay = require("./routeList/video-display");
const getInitialInfo = require("./routeList/getInitialInfo");
const getTranscription = require("./routeList/getTranscription");
const removeAudio = require("./routeList/remove-audio");
const unload = require("./routeList/unload");
const replaceaudio = require("./routeList/replace-audio");
const unlinkvideo = require("./routeList/unlink-video");
const insertText = require("./routeList/insert-text");
const importAudio = require("./routeList/import-audio");
const getAssets = require("./routeList/getAssets");
const audioStream = require("./routeList/audioStream");
const replaceAudioLocal = require("./routeList/replace-audio-local");
const router = express.Router();

module.exports = () => {
    router.use("/signin", signinRoute());
    router.use("/signup",signupRoute());
    router.use("/create-project",authenticateToken(), createNewProject());
    router.use("/retrieve-projects", authenticateToken(), retrieveProject());
    router.use("/edit-project", authenticateToken(), editDetail());
    router.use("/delete-project", authenticateToken(), deleteProject());
    router.use("/upload-video", authenticateToken(), uploadVideo());
    router.use("/video-display", videoDisplay());
    router.use("/get-initial-info", authenticateToken(), getInitialInfo());
    router.use("/get-transcription", getTranscription());
    router.use("/remove-audio", authenticateToken(), removeAudio());
    router.use("/unload", unload());
    router.use("/replace-audio",authenticateToken(), replaceaudio());
    router.use("/unlink-video", unlinkvideo());
    router.use("/insert-text", authenticateToken(), insertText());
    router.use("/import-audio", authenticateToken(), importAudio());
    router.use("/get-assets", authenticateToken(), getAssets());
    router.use("/get-audio", audioStream());
    router.use("/replace-audio-local",authenticateToken(), replaceAudioLocal());
    return router;
}